CREATE TABLE IF NOT EXISTS USERS(
	USERNAME VARCHAR(50) PRIMARY KEY,
	PASSWORD VARCHAR(100),
	EMAIL VARCHAR(50),
	NAME VARCHAR(20),
	TYPE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TURNO(
	EDIFICIOS VARCHAR(5),
	ID VARCHAR(5) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS HORARIOS(
	SALON VARCHAR(4),
	HORAINICIO VARCHAR(7),
	HORAFIN VARCHAR(7),
	DIA VARCHAR(15),
	EDIFICIO VARCHAR(1),
	TURNO_ID VARCHAR(5),
	CONSTRAINT FK_TURNO FOREIGN KEY (TURNO_ID) REFERENCES TURNO(ID)
);


