CREATE TABLE IF NOT EXISTS USERS(
	USERNAME VARCHAR(50) PRIMARY KEY,
	PASSWORD VARCHAR(100),
	EMAIL VARCHAR(50),
	NAME VARCHAR(20),
	TYPE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TURNOS(
	EDIFICIOS VARCHAR(5) NOT NULL,
	DIA VARCHAR(9) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	ID VARCHAR(5) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS APERTURAS(
	SALON VARCHAR(4),
	HORA_INICIO VARCHAR(7),
	HORA_FIN VARCHAR(7),
	EDIFICIO VARCHAR(1),
	TURNO_ID VARCHAR(5),
	CONSTRAINT FK_TURNO FOREIGN KEY (TURNO_ID) REFERENCES TURNO(ID)
);




