CREATE TABLE IF NOT EXISTS USERS(
	USERNAME VARCHAR(50) PRIMARY KEY,
	PASSWORD VARCHAR(100),
	EMAIL VARCHAR(50),
	NAME VARCHAR(20),
	TYPE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TURNOS(
	EDIFICIOS VARCHAR(5) NOT NULL,
	DIA VARCHAR(9) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	LAST_ACCESS TIME NOT NULL,
	ESTADO VARCHAR(7),
	ID SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS APERTURAS(
	EDIFICIO VARCHAR(1) NOT NULL,
	SALON VARCHAR(4) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	DIA VARCHAR(9) NOT NULL,
	ID SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS HORARIOS(
	SALON VARCHAR(4) NOT NULL,
	HORA TIME NOT NULL,
	TIPO VARCHAR(8) NOT NULL,
	EDIFICIO VARCHAR(1) NOT NULL,
	ESTADO VARCHAR(9) NOT NULL,
	APERTURA_ID INTEGER REFERENCES APERTURAS(ID),
	DIA VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS TURNO_MONITOR(
	USERNAME VARCHAR(50) REFERENCES USERS(USERNAME),
	ID INTEGER REFERENCES TURNOS(ID) 
);


